swagger: "2.0"
info:
  description: "The content ingestion services (CIS) are used by EPA to power records management applications."
  version: "0.0.1"
  title: "EPA Content Ingestion Services"
  contact:
    email: "yuen.andrew@epa.gov"
host: "localhost:8000"
basePath: "/"
tags:
- name: "record_schedules"
  description: "APIs to access record schedule information."
- name: "desktop"
  description: "APIs to support desktop file upload"
- name: "email"
  description: "APIs to support email file upload"
- name: "my_records"
  description: "APIs for users to access their records"
- name: "settings"
  description: "APIs to access and edit user settings"
- name: "schedule_predictions"
  description: "All APIs that provide record schedule recommendations."
schemes:
- "http"
paths:
  /file_metadata_prediction:
    post:
      tags:
      - "schedule_predictions"
      - "desktop"
      summary: "Gets record schedule, title, and description recommendations for a document."
      consumes:
        - "multipart/form-data"
      parameters:
        - in: "formData"
          name: "file"
          type: "file"
          description: "The file to get recommendations for."
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "Recommendations were successfully given."
          schema:
            $ref: "#/definitions/MetadataPrediction"
  /text_metadata_prediction:
    post:
      tags:
      - "schedule_predictions"
      summary: "Gets record schedule recommendation for given text."
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "TextPredictionRequest"
          schema: 
            $ref: "#/definitions/TextPredictionRequest"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "Recommendations were successfully given."
          schema:
            $ref: "#/definitions/MetadataPrediction"
  /email_metadata_prediction:
    get:
      tags:
      - "schedule_predictions"
      - "email"
      summary: "Gets metadata recommendations for given email."
      consumes:
        - "application/json"
      parameters:
        - in: "query"
          name: "email_id"
          type: "string"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "header"
          name: "X-Access-Token"
          type: "string"
          required: true
      responses:
        "200":
          description: "Recommendations were successfully given."
          schema:
            $ref: "#/definitions/MetadataPrediction"
  /upload_file:
    post:
      tags:
      - "desktop"
      summary: "Upload a file to ECMS with metadata."
      consumes:
        - "multipart/form-data"
      parameters:
        - in: "formData"
          name: "file"
          type: "file"
          description: "The file to get recommendations for."
        - in: "formData"
          name: "metadata"
          type: "string"
          description: "String of serialized JSON with ECMS metadata."
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "File was successfully uploaded."
          schema:
            $ref: "#/definitions/StatusResponse"
  /get_mailboxes:
    get:
      tags:
      - "email"
      summary: "List the mailboxes to which the user has access."
      consumes:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "Mailboxes successfully listed."
          schema:
            $ref: "#/definitions/GetMailboxesResponse"
  /get_emails:
    get:
      tags:
      - "email"
      summary: "List the emails in a given mailbox."
      consumes:
        - "application/json"
      parameters:
        - in: "query"
          name: "mailbox"
          type: "string"
        - in: "query"
          name: "count"
          type: "integer"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "header"
          name: "X-Access-Token"
          type: "string"
          required: true
      responses:
        "200":
          description: "Emails successfully retrieved."
          schema:
            $ref: "#/definitions/GetEmailResponse"
  /describe_email:
    get:
      tags:
      - "email"
      summary: "Get the details for a specific email."
      consumes:
        - "application/json"
      parameters:
        - in: "query"
          name: "email_id"
          type: "string"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "header"
          name: "X-Access-Token"
          type: "string"
          required: true
      responses:
        "200":
          description: "Email information provided."
          schema:
            $ref: "#/definitions/DescribeEmailResponse"
  /upload_email:
    post:
      tags:
        - "email"
      summary: "Upload email to ECMS with metadata."
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "upload_request"
          schema: 
            $ref: "#/definitions/UploadEmailRequest"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "header"
          name: "X-Access-Token"
          type: "string"
          required: true
      responses:
        "200":
          description: "Email successfully uploaded."
          schema:
            $ref: "#/definitions/StatusResponse"
  /download_email:
    get:
      tags:
      - "email"
      summary: "Download an email as an EML file."
      consumes:
        - "application/json"
      parameters:
        - in: "query"
          name: "file_name"
          type: "string"
        - in: "query"
          name: "email_id"
          type: "string"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "header"
          name: "X-Access-Token"
          type: "string"
          required: true
      responses:
        "200":
          description: "EML file downloaded."
          schema:
            type: "file"
  /mark_email_saved:
    post:
      tags:
      - "email"
      summary: "Mark an email with the saved tag in Outlook."
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "MarkSavedRequest"
          schema: 
            $ref: "#/definitions/MarkSavedRequest"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "header"
          name: "X-Access-Token"
          type: "string"
          required: true
      responses:
        "200":
          description: "Email marked as saved."
          schema:
            $ref: "#/definitions/StatusResponse"
  /untag_email:
    post:
      tags:
      - "email"
      summary: "Remove record tag in Outlook."
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "UntagRequest"
          schema: 
            $ref: "#/definitions/UntagRequest"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "header"
          name: "X-Access-Token"
          type: "string"
          required: true
      responses:
        "200":
          description: "Record tag for email has been removed."
          schema:
            $ref: "#/definitions/StatusResponse"
  /get_favorites:
    get:
      tags:
      - "settings"
      summary: "Get record schedules favorited by user."
      consumes:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "Favorites were added."
          schema:
            $ref: "#/definitions/GetFavoritesResponse"
  /add_favorites:
    post:
      tags:
      - "settings"
      summary: "Add favorites for user."
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "favs"
          description: "Lan ID for the user whose favorites are to be added and the IDs of the new favs."
          schema:
            $ref: "#/definitions/AddFavoritesRequest"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "Favorites were added."
          schema:
            $ref: "#/definitions/StatusResponse"
        "500":
          description: "Server side failure with explanation."
          schema:
            $ref: "#/definitions/StatusResponse"
  /remove_favorites:
    post:
      tags:
      - "settings"
      summary: "Remove favorites for user."
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "RemoveFavoritesRequest"
          description: "Lan ID for the user whose favorites are to be removed and the IDs of the favs."
          schema:
            $ref: "#/definitions/RemoveFavoritesRequest"
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "Favorites were removed."
          schema:
            $ref: "#/definitions/StatusResponse"
        "500":
          description: "Server side failure with explanation."
          schema:
            $ref: "#/definitions/StatusResponse"
  /get_record_schedules:
    get:
      tags:
      - "record_schedules"
      summary: "Get record schedule information."
      consumes:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "Record schedule information retrieved."
          schema:
            $ref: "#/definitions/StatusResponse"
  /my_records:
    get:
      tags:
      - "my_records"
      summary: "Get information for existing records."
      consumes:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "query"
          name: "lan_id"
          type: "string"
          required: true
        - in: "query"
          name: "items_per_page"
          type: "number"
          required: true
        - in: "query"
          name: "page_number"
          type: "number"
          required: true
      responses:
        "200":
          description: "Record information retrieved."
          schema:
            $ref: "#/definitions/DocumentumRecordList"
  /my_records_count:
    get:
      tags:
      - "my_records"
      summary: "Get count of existing records for the user."
      consumes:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
      responses:
        "200":
          description: "Record count retrieved."
          schema:
            $ref: "#/definitions/RecordCountResponse"
  /my_records_download:
    get:
      tags:
      - "my_records"
      summary: "Download existing records."
      consumes:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          format: "jwt"
          required: true
        - in: "query"
          name: "lan_id"
          type: "string"
          required: true
        - in: "query"
          name: "object_ids"
          type: "array"
          items:
            type: "string"
          required: true
      responses:
        "200":
          description: "Records zip file downloaded."
          schema:
            type: "file"
definitions:
  MetadataPrediction:
    type: "object"
    properties:
      predicted_schedules:
        type: "array"
        items: 
          type: "object"
          properties:
            schedule: 
              $ref: "#/definitions/RecordSchedule"
            probability:
              type: "number"
      title:
        type: "object"
        properties:
          value: 
            type: "string"
          prediction_type:
            type: "string"
      description:
        type: "object"
        properties:
          value: 
            type: "string"
          prediction_type:
            type: "string"
  AddFavoritesRequest:
    type: "object"
    properties:
      record_schedules:
        type: "array"
        items: 
          $ref: "#/definitions/RecordSchedule"
  RemoveFavoritesRequest:
    type: "object"
    properties:
      record_schedules:
        type: "array"
        items: 
          $ref: "#/definitions/RecordSchedule"
  StatusResponse:
    type: "object"
    properties:
      status:
        type: "string"
      reason: 
        type: "string"
  TextPredictionRequest:
    type: "object"
    properties:
      text:
        type: "string"
  GetMailboxesResponse:
    type: "object"
    properties:
      mailboxes:
        type: "array"
        items: 
          type: "string"
  GetEmailResponse:
    type: "object"
    properties:
      total_count: 
        type: "integer"
      emails:
        type: "array"
        items:
          type: "object"
          properties:
            unid:
              type: "string"
            email_id: 
              type: "string"
            _from:
              type: "string"
            to:
              type: "string"
            subject:
              type: "string"
            sent:
              type: "string"
            received:
              type: "string"
  DescribeEmailResponse:
    type: "object"
    properties:
      email_id: 
        type: "string"
      _from:
        type: "string"
      to:
        type: "string"
      subject:
        type: "string"
      sent:
        type: "string"
      received:
        type: "string"
      body:
        type: "string"
      attachments:
        type: "array"
        items:
          type: "string"  
  UploadEmailRequest:
    type: "object"
    properties:
      email_id:
        type: "string"
      metadata:
        $ref: "#/definitions/ECMSMetadata"
  MarkSavedRequest:
    type: "object"
    properties:
      email_id:
        type: "string"
      sensitivity:
        type: "string"
        enum: ["shared", "private"]
  UntagRequest:
    type: "object"
    properties:
      email_id:
        type: "string"
  ECMSMetadata:
    type: "object"
    properties:
      title: 
        type: "string"
      description:
        type: "string"
      record_schedule:
        $ref: "#/definitions/RecordSchedule"
      creator: 
        type: "string"
      creation_date: 
        type: "string"
      sensitivity:
        type: "string"
        enum: ["shared", "private"]
      rights:
        type: "string"
      coverage:
        type: "string"
  RecordSchedule:
    type: "object"
    properties:
      function_number: 
        type: "string"
      schedule_number: 
        type: "string"
      disposition_number: 
        type: "string"
  RecordScheduleInformation:
    type: "object"
    properties:
      function_number: 
        type: "string"
      schedule_number: 
        type: "string"
      disposition_number: 
        type: "string"
      display_name:
        type: "string"
      schedule_title: 
        type: "string" 
      disposition_title:
        type: "string" 
      disposition_instructions:
        type: "string" 
      cutoff_instructions:
        type: "string" 
      function_title:
        type: "string" 
      program:
        type: "string" 
      applicability:
        type: "string" 
      nara_disposal_authority_item_level:
        type: "string" 
      nara_disposal_authority_schedule_level:
        type: "string" 
      final_disposition:
        type: "string" 
      disposition_summary:
        type: "string" 
      description:
        type: "string" 
      guidance:
        type: "string" 
      keywords:
        type: "string" 
  GetFavoritesResponse:
    type: "object"
    properties:
      favorites:
        type: "array"
        items:
          $ref: "#/definitions/RecordSchedule"
  GetRecordSchedulesResponse:
    type: "object"
    properties:
      schedules:
        type: "array"
        items:
          $ref: "#/definitions/RecordScheduleInformation"
  DocumentumDocInfo:
    type: "object"
    properties:
      title: 
        type: "string"
      doc_type: 
        type: "string"
      date: 
        type: "string"
      sensitivity:
        type: "string"
      doc_id:
        type: "string"
      object_ids: 
        type: "array"
        items: 
          type: "string"
      size: 
        type: "number"
      custodian:
        type: "string"
  DocumentumRecordList:
    type: "object"
    properties:
      has_next:
        type: "boolean"
      records:
        type: "array"
        items: 
          $ref: "#/definitions/DocumentumDocInfo"
  RecordCountResponse:
    type: "object"
    properties:
      count:
        type: "number"

